// ! Feel free to explore this file, but do not modify anything here!
const pokemon = [
  { number: 1, name: 'Bulbasaur', type: 'grass', hp: 45, starter: true },
  { number: 2, name: 'Ivysaur', type: 'grass', hp: 60, starter: false },
  { number: 3, name: 'Venusaur', type: 'grass', hp: 80, starter: false },
  { number: 4, name: 'Charmander', type: 'fire', hp: 39, starter: true },
  { number: 5, name: 'Charmeleon', type: 'fire', hp: 58, starter: false },
  { number: 6, name: 'Charizard', type: 'fire', hp: 78, starter: false },
  { number: 7, name: 'Squirtle', type: 'water', hp: 44, starter: true },
  { number: 8, name: 'Wartortle', type: 'water', hp: 59, starter: false },
  { number: 9, name: 'Blastoise', type: 'water', hp: 79, starter: false },
  { number: 10, name: 'Caterpie', type: 'bug', hp: 45, starter: false },
  { number: 11, name: 'Metapod', type: 'bug', hp: 50, starter: false },
  { number: 12, name: 'Butterfree', type: 'bug', hp: 60, starter: false },
  { number: 13, name: 'Weedle', type: 'bug', hp: 40, starter: false },
  { number: 14, name: 'Kakuna', type: 'bug', hp: 45, starter: false },
  { number: 15, name: 'Beedrill', type: 'bug', hp: 65, starter: false },
  { number: 16, name: 'Pidgey', type: 'normal', hp: 40, starter: false },
  { number: 17, name: 'Pidgeotto', type: 'normal', hp: 63, starter: false },
  { number: 18, name: 'Pidgeot', type: 'normal', hp: 83, starter: false },
  { number: 19, name: 'Rattata', type: 'normal', hp: 30, starter: false },
  { number: 20, name: 'Raticate', type: 'normal', hp: 55, starter: false },
  { number: 21, name: 'Spearow', type: 'normal', hp: 40, starter: false },
  { number: 22, name: 'Fearow', type: 'normal', hp: 65, starter: false },
  { number: 23, name: 'Ekans', type: 'poison', hp: 35, starter: false },
  { number: 24, name: 'Arbok', type: 'poison', hp: 60, starter: false },
  { number: 25, name: 'Pikachu', type: 'electric', hp: 35, starter: true },
  { number: 26, name: 'Raichu', type: 'electric', hp: 60, starter: false }
];
